repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '/home/vanessac/miniconda3/envs/queue/bin/python3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]